import { etiquetas, propiedad, qid, urlEntidad } from './wikidata.mjs';
import { WIKIDATA, POPULARIDAD_WIKIPEDIA, exigir } from './ayudas.mjs';
import { limpiarAlias } from './comun.mjs';
export const AUTORES=[{id:'autores',nombre:'Autores ganadores del Nobel y Cervantes',descripcion:'Unión de dos catálogos de premios cerrados conservados, con atributos de Wikidata.',popularidad:POPULARIDAD_WIKIPEDIA,depende:['nobel_literatura','premio_cervantes'],cobertura:{tipo:'completa',criterio:'Unión de todas las personas de los catálogos verificados Nobel de Literatura y Premio Cervantes guardados en el repositorio, sin agregar otros premios incompletos.'},atributos:{premios:{tipo:'lista',etiqueta:'premio'},nacionalidades:{tipo:'lista',etiqueta:'nacionalidad'},idiomas:{tipo:'lista',etiqueta:'idioma de escritura'}},async importar({hoy,catalogos}){
 const ids=new Map();for(const [catalogo,premio]of [['nobel_literatura','Nobel de Literatura'],['premio_cervantes','Premio Cervantes']])for(const e of catalogos[catalogo].entidades){const id=e.id??qid(e.fuente);if(!/^Q\d+$/.test(id))throw Error(`${e.nombre}: sin Wikidata`);ids.set(id,[...(ids.get(id)??[]),premio]);}
 const et=await etiquetas([...ids.keys()]),nacs=await propiedad([...ids.keys()],'P27'),idiomas=await propiedad([...ids.keys()],'P6886');const lista=(m,id)=>{const v=m.get(id);return v?.length&&v.every(x=>x.valor.nombre)?[...new Set(v.map(x=>x.valor.nombre))]:null;};
 const entidades=[...ids].map(([id,premios])=>{const e=et.get(id);if(!e.es)throw Error(`${id}: sin nombre`);return {id,nombre:e.es,alias:limpiarAlias(e.es,e.alias),popularidad:e.enlaces,atributos:{premios,nacionalidades:lista(nacs,id),idiomas:lista(idiomas,id)},fuente:urlEntidad(id)};});const verificacion=[];exigir(entidades.filter(e=>e.atributos.premios.includes('Nobel de Literatura')).length===catalogos.nobel_literatura.entidades.length,'Nobel: todas las personas del catálogo original',verificacion);exigir(entidades.filter(e=>e.atributos.premios.includes('Premio Cervantes')).length===catalogos.premio_cervantes.entidades.length,'Cervantes: todas las personas del catálogo original',verificacion);
 return {entidades,verificacion,fuentes:[WIKIDATA],hoy};
}}];
