import { etiquetas, sparql, propiedad, qid, anio, urlEntidad } from './wikidata.mjs';
import { idsDePaginas } from './wikipedia_entidades.mjs';
import { WIKIDATA, POPULARIDAD_WIKIPEDIA, exigir } from './ayudas.mjs';
import { limpiarAlias } from './comun.mjs';
const SAGAS=[['Uncharted',4,['Uncharted: Drake\'s Fortune','Uncharted 2: Among Thieves','Uncharted 3: Drake\'s Deception','Uncharted 4: A Thief\'s End']],['BioShock',3,['BioShock','BioShock 2','BioShock Infinite']],['Mass Effect',4,['Mass Effect (video game)','Mass Effect 2','Mass Effect 3','Mass Effect: Andromeda']],['Age of Empires',4,['Age of Empires (video game)','Age of Empires II','Age of Empires III','Age of Empires IV']]];
export const VIDEOJUEGOS=[{id:'videojuegos',nombre:'Videojuegos de sagas verificadas',descripcion:'Sagas de Wikidata con miembros lanzados y anclas verificadas; sin prometer todos los juegos de Mario.',popularidad:POPULARIDAD_WIKIPEDIA,cobertura:{tipo:'parcial',criterio:'Juegos lanzados con fecha registrada en Wikidata y relación P179/P8345 a las sagas admitidas. Se verifican las entregas principales como anclas y se conservan también derivados; no todas las franquicias.'},atributos:{franquicias:{tipo:'lista',etiqueta:'franquicia'},anio:{tipo:'numero',etiqueta:'año de lanzamiento'},desarrolladoras:{tipo:'lista',etiqueta:'desarrolladora'},generos:{tipo:'lista',etiqueta:'género'},plataformas:{tipo:'lista',etiqueta:'plataforma'}},async importar({hoy}){
 const semillas=await idsDePaginas(SAGAS.map(([n])=>n)),etSem=await etiquetas([...semillas.values()]);const filas=[],verificacion=[],sinVerificar=[];const admitidas=[];
 for(const [nombre,min,anclas]of SAGAS){const id=semillas.get(nombre);if(!id)continue;const fs=await sparql(`SELECT DISTINCT ?i WHERE { { ?i wdt:P179 wd:${id} } UNION { ?i wdt:P8345 wd:${id} } ?i wdt:P31/wdt:P279* wd:Q7889 ; wdt:P577 ?fecha . FILTER(?fecha <= "${hoy}T23:59:59Z"^^xsd:dateTime) }`);const esperados=await idsDePaginas(anclas);if(fs.length<min||[...esperados.values()].some(id=>!fs.some(f=>qid(f.i)===id))){sinVerificar.push(`${nombre}: ${fs.length} miembros; no están todas las ${min} entregas ancla. Saga descartada.`);continue;}admitidas.push(etSem.get(id).es??nombre);filas.push(...fs.map(f=>({...f,saga:etSem.get(id).es??nombre})));verificacion.push(`${nombre}: ${fs.length} juegos lanzados, ${min} anclas presentes`);}
 exigir(admitidas.length>0,'al menos una saga verificada',verificacion);const ids=[...new Set(filas.map(f=>qid(f.i)))],et=await etiquetas(ids),fecha=await propiedad(ids,'P577'),dev=await propiedad(ids,'P178'),genero=await propiedad(ids,'P136'),plataforma=await propiedad(ids,'P400');const lista=(m,id)=>{const v=m.get(id);return v?.length&&v.every(x=>x.valor.nombre)?[...new Set(v.map(x=>x.valor.nombre))]:null;};
 const entidades=ids.map(id=>{const w=et.get(id),nombre=w.es??w.en;if(!nombre)throw Error(`${id}: sin título`);return {id,nombre,alias:limpiarAlias(nombre,[...w.alias,w.en]),popularidad:w.enlaces,atributos:{franquicias:[...new Set(filas.filter(f=>qid(f.i)===id).map(f=>f.saga))],anio:Math.min(...fecha.get(id).map(f=>anio(f.valor)).filter(n=>n!==null)),desarrolladoras:lista(dev,id),generos:lista(genero,id),plataformas:lista(plataforma,id)},fuente:urlEntidad(id)};});
 return {entidades,verificacion,sinVerificar,cobertura:{completoPor:{franquicias:admitidas}},fuentes:[WIKIDATA],hoy};
}}];
